name: 'PR Template Validtor'
description: |
  This action allows for verifying if a Pull Request matches required template
author: 'Mikołaj Nowak <mikolaj.nowak@konghq.com>'

branding:
  icon: 'git-pull-request'
  color: 'blue'

# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

# # Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
